block_labels = [
    "S-do-not-merge-yet",
    "S-needs-tests",
    "S-work-in-progress",
    ]

delete_merged_branches = true

status = [
    "codecov/patch",
    "codecov/project",
    "continuous-integration/travis-ci/push",
]

timeout_sec = 576000
